### ISSUE TITLE
Problème de déconnection avec le SSO

### ISSUE THREAD

**Issue by tchoyy** [jbl2024/latelier#112]
Bonjour,

Nous avons configuré une instance de latelier en SSO selon l'attribut mail qui est passé, cela fonctionne très bien.
Par contre le bouton déconnexion revient à chaque fois sur l'interface de latelier.
Comment pouvons nous définir une URL de retour ?
J'ai bien vu un paramètre pour l'authentification oauth mais rien pour la partie SSO

Merci.

**Comment by jbl2024** [comment]
Bonne question :)

Je regarde cela dès que possible.
