### ISSUE TITLE
Problème de fuseau horaire à la création de réunions

### ISSUE THREAD

**Issue by glaville** [jbl2024/latelier#113]
Bonjour

En installant et configurant l'application latelier, tout fonctionne très bien et la solution est vraiment complète,
mais un bug gênant se produit en créant des réunions :

La fenêtre initiale affiche bien l'heure souhaitée dans la première boîte de dialogue (07:15 à 7:45 par exemple), mais après appui sur le bouton "Créer" , la page d'édition de l'Ordre du jour, du Compte-rendu et du Relevé de décisions indique en haut à gauche un créneau décalé d'une heure, de 08:15 à 8:45.

Retourner sur l'agenda des réunions confirme ce décalage : la réunion est à présent affichée également pour une heure plus tard.

Forcer le navigateur en fuseau horaire UTC semble produire le comportement inverse : la réunion "avance" une heure plus tôt (06:15 à 06:45 avec l'exemple), ce qui laisse penser qu'il s'agit d'un problème de conversion à un moment donné entre heure du navigateur et heure serveur.

Le bug est également présent et peut être reproduit sur l'instance de démonstration https://latelier.services.jbl2024.com,
ce qui laisse penser que le problème n'est pas avec notre déploiement spécifiquement.

Merci

**Comment by jbl2024** [comment]
ok bien noté merci pour le retour

je check cela.

**Comment by glaville** [comment]
Merci : je viens de récupérer via un git pull les derniers changements sur la branche master (commit 71290cd902a1e9c67abae8b3f2e7894b4bd4645d).

Cependant, après `docker-compose build`, suivi d'un `docker-compose down` puis `docker-compose up -d`, le bug est toujours présent (avec un décalage de deux heures cette fois, une réunion placée à partir de 8h passe à présent à 10h).

Est-ce normal ?

`docker images` me confirme que l'image utilisée par les conteneurs est bien celle buildée il y a quelques minutes avec les corrections, et même chose pour les conteneurs eux-mêmes.

**Comment by mhdbaal** [comment]
Bonjour, est-ce que vous constatez aussi ce problème sur l'instance de démonstration (qui a été mise à jour) ?

https://latelier.services.jbl2024.com/login
user1@localhost / user1

Peut-être aussi essayer un `docker-compose build --no-cache` si c'est une option envisageable ?

Merci

**Comment by glaville** [comment]
Bonjour

Effectivement le bug n'est plus présent avec mon navigateur sur l'instance de démo.

Un `docker-compose build --no-cache` n'a pas suffit à résoudre le problème, mais il provenait en fait d'une modification manuelle du fichier imports/ui/meetings/Meeting/MeetingEdit.vue pour élargir les horaires de réunion autorisés de 5h à 22h.

Cela avait bloqué la mise à jour du fichier, et donc de l'ajout de DateMixins : après l'avoir réinitialisé, et à nouveau reconstruit l'image, tout fonctionne correctement.

Merci beaucoup pour vos retours et votre réactivité !

Bonne journée

**Comment by mhdbaal** [comment]
Ah c'est une bonne nouvelle!
merci également pour les retours

Bonne journée
