### ISSUE TITLE
Wrong month translation in Task properties

### ISSUE THREAD

**Issue by fatah-fple** [jbl2024/latelier#142]
**Describe the bug**
Wrong month translation in Task properties

**To Reproduce**
1. in task list, select start or end date

**Expected behavior**
For en lang, should have months name in english

**Screenshots**
![image](https://user-images.githubusercontent.com/73150341/157592666-37c5102d-0b21-4b0b-ac5a-bb06e53615d3.png)

**Comment by jbl2024** [comment]
Thank you for your report.

Yes indeed we still have hardcoded messages in some places. I'm working on it.

**Comment by vincentpricex** [comment]
Bonsoir,

any update about it?

**Comment by jbl2024** [comment]
Hi, it's fixed in last release
