### ISSUE TITLE
Lot of account with real mail are present on first start

### ISSUE THREAD

**Issue by Dryusdan** [jbl2024/latelier#18]
Hi

I test your application, and I found a problem in admin panel : Lot of real mail are present on first start.

![Capture d’écran du 2019-07-02 16-05-43](https://user-images.githubusercontent.com/4410431/60519505-fe54f280-9ce3-11e9-90d8-355efbda209a.png)

I think is not good for privacy :)
And It's surprise me on fresh install.

So, is it possible to delete these accounts at the first installation?

Regards

**Comment by jbl2024** [comment]
Hi,
those accounts are fakes and generated at startup (see generateFixtures in https://github.com/jbl2024/latelier#configuration). It was a way for me to test the application with some kind of data.

Do you have set up a config file with this parameter set ?

Best regards

**Comment by Dryusdan** [comment]
Okay, thank you :)

Yes, generateFixture is set to true so, the website generate fakedata :sweat_smile: 

Thank for your anwser
