### ISSUE TITLE
Left sidebar is on main block

### ISSUE THREAD

**Issue by Dryusdan** [jbl2024/latelier#19]
Hi,

I found a little CSS problem : the sidebar is on the main block, so it's hidding a lot of information, form...

![Capture d’écran du 2019-07-02 16-23-32](https://user-images.githubusercontent.com/4410431/60522169-c9976a00-9ce8-11e9-8be1-899652365139.png)
I think a `margin-left` with value `5%` is good in `.v-content__wrap` class (I test this value in firefox dev tools).
Also I have a full HD screen (1920x1080).

Regards

**Comment by Dryusdan** [comment]
Okay, I found the problem : XHR request.

For a unknown reason, the app prefer use IP of server instead ROOT_URL ( https://docs.meteor.com/environment-variables.html ).
I search into the code :)

**Comment by Dryusdan** [comment]
Ok, I found. 
I must define these two environment variable : 
```
HMR_URL=https://kanban.test
```
The `HMR_URL` is needed for socket.io, now it use this domain with https on port 443.

But some ressource always call on URL localhost:3000, only image

**Comment by Dryusdan** [comment]
Hi

I am actually blocked.

`Meteor.absoluteUrl()` return always `http://localhost:3000`. The environment variable `ROOT_URL` is set .
I try to force URL with `__meteor_runtime_config__.ROOT_URL` in `server/main.js` or `client/main.js` and is no effect...
Can you help me ? :)

**Comment by jbl2024** [comment]
You can try this command instead of `npm start` :

`meteor run --settings settings-development.json --port http://kanban.test:80`

**Comment by Dryusdan** [comment]
This command send me an error :
```
Can't listen on host kanban.test
(EADDRNOTAVAIL from listen).
```

Actually I test on vm on private network with a reverse proxy with public IP.
But on a local network is the same problem 

Thank for your help :)

**Comment by jbl2024** [comment]
For this kind of setup i usually put nginx in front of my app 

Do not forget to set ROOT_URL to https://kanban.test.

Configuration example below:

```
upstream latelier_server {
    server 127.0.0.1:3000 fail_timeout=0;
}

server {
  listen 80;
  server_name kanban.test;
  # enforce https
  return 301 https://kanban.test$request_uri;
}


server {
     listen 443 ssl;
     server_name kanban.test;
     client_max_body_size 10M;
     access_log  /var/log/nginx/kanban.test.access.log;
     ssl_certificate /etc/nginx/ssl/yourcertificate.fr.crt;
     ssl_certificate_key /etc/nginx/ssl/yourcertificate.fr.key;
     location / {
        proxy_pass http://latelier_server;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade; # allow websockets
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header X-Forwarded-For $remote_addr; # preserve client IP
        proxy_buffering off;
        proxy_request_buffering off;

        # this setting allows the browser to cache the application in a way compatible with Meteor
        # on every application update the name of CSS and JS file is different, so they can be cache infinitely (here: 30 days)
        # the root path (/) MUST NOT be cached
        if ($uri != '/') {
            expires 30d;
        }
    }
}
`

**Comment by Dryusdan** [comment]
I have a Nginx in front, the conf look the same.
But app request .svg and .ico by localhost:3000.
ROOT_URL is defined :)

**Comment by jbl2024** [comment]
Maybe it is related to hot module reload 
Do you have any messages in the browser console ?
Does the HMR host and port displayed in console (Dev server URL) match the values displayed in your shell when launching the app ?

**Comment by jbl2024** [comment]
closing due to inactivy
