### ISSUE TITLE
[Question] What is Fixture ?

### ISSUE THREAD

**Issue by Dryusdan** [jbl2024/latelier#20]
Hi (I say, I open too issues, but project look good :) )

I have somes questions with option `generateFixtures` : what is a Fixture ? Is it possible to generate this with the command `npm build` (for exemple) ?
Is this option who take 2Go of RAM and 50% CPU on 2 vCPU ?

Regards,

**Comment by jbl2024** [comment]
Hi,
thank you for your feedback!

Fixtures are fake data generated at startup, it can be helpful to test application. 

The code  where fake users are generated is located here : https://github.com/jbl2024/latelier/blob/master/imports/startup/server/fixtures.js

Regards

**Comment by Dryusdan** [comment]
Okay, thank you for your anwser. :)
