### ISSUE TITLE
[i18n] Possibility to display various languages

### ISSUE THREAD

**Issue by Quenty31** [jbl2024/latelier#21]
Would it be possible to offer different languages?
I couldn’t find the internalisation files so I guess it wasn’t planned.

**Comment by jbl2024** [comment]
i18n is handled at 2 levels:

- a global i18n.js file for common terms: https://github.com/jbl2024/latelier/blob/master/imports/i18n.js
- at component level you can find i18n dict : example here https://github.com/jbl2024/latelier/blob/master/client/components/bpmn/NewProcessDiagram.vue#L47

btw some terms are not yet translated (error messages in form for example).

I honestly don't know if this is a good way to handle it, feel free to suggest a better approach.

Best regards

**Comment by Quenty31** [comment]
Hello,
usually they put a file per language so they don't mix.
I've just made a PR. But I'm wondering something about the dates, you seem to use moment.
The Occitan is only included in the development version so far =/

**Comment by jbl2024** [comment]
Hi,
i have merged your contribution. 
I think i will move all the i18 dict in component into the global i18n.js file. It will be easier to manage finally.

**Comment by Quenty31** [comment]
Cool, merci beaucoup !
