### ISSUE TITLE
"v-navigation-drawer" scroll is not hidden

### ISSUE THREAD

**Issue by sabatale** [jbl2024/latelier#71]
The overflow does not seem to work for me, at least on Edge (Chromium version). Removing the overflow-* attributes makes the scrollbar disappear. Replacing them with overflow: hidden works as well.

```
.v-navigation-drawer__content {
    height: 100%;
    overflow-y: auto;
    overflow-x: hidden;
}
```

![image](https://user-images.githubusercontent.com/50220345/76810668-4611a080-67c5-11ea-969e-91fc597cf256.png)

**Comment by jbl2024** [comment]
Hi,
thank you for  you feedback.

Do you have the issue with another browser too (ff or chrome) ?

**Comment by sabatale** [comment]
Hey there,

Same, yes! 1920x1080 resolution.

![image](https://user-images.githubusercontent.com/50220345/76857892-c15a6d00-682c-11ea-8b2d-963920d39830.png)

**Comment by jbl2024** [comment]
Is it related to https://github.com/vuetifyjs/vuetify/issues/1197 ?

Btw adding your proprosed css does not change anything on my dev env:( 
Could you make a PR so that i could test it further ?

**Comment by niti2539** [comment]
v-navigation-drawer generate the  new div with v-navigation-drawer__content class so you have to 1. add  style " style="overflow-y: hidden;" "  in the v-navigation-drawer  and
 2. add  style to class "v-navigation-drawer__content" in style section
like this 
.v-navigation-drawer__content{
  overflow-y: hidden !important;
}

**Comment by mhdbaal** [comment]
Hi,

You should check out the new 3.0.0 beta.1 release here : https://github.com/jbl2024/latelier/releases/tag/v3.0.0-beta.1

It contains several UI improvements and fixes, and especially a better use of screen estate in large desktop (such as 1920x1080)
Related to your issue, the scrollbar issue you mention also no longer exists in this version.

If changing the UI and version is definitely not an option for you, you could also use some of the solution given above by @niti2539

**Comment by arbutt76** [comment]
**At Chrome:**
I tried this

.v-navigation-drawer__content {
    height: 100%;
    overflow-y: auto;
    overflow-x: hidden;
}

Version 87.0.4280.141 (Official Build) (64-bit)
Then I simply wrote

<v-navigation-drawer
    height="auto"
    >

It worked but I am using Vuetify version 1.5 something 
Hopefully, it will help people who don't know
Thanks
Abdul
