### ISSUE TITLE
Tri des taches

### ISSUE THREAD

**Issue by yoyo2000** [jbl2024/latelier#84]
Dans le tableau des taches, la colonne qui "attrape" les taches terminées se remplit très vite.
Il serait préférable de la trier avec les taches récentes en haut pour éviter de scroller jusqu'en bas pour voir les dernières arrivées.

**Comment by jbl2024** [comment]
Effectivement, c'est une bonne suggestion

**Comment by jbl2024** [comment]
Fixed in https://github.com/jbl2024/latelier/commit/0b06df6562e796310d8c268e7c475f367501792c
